# Generated by Django 5.0.6 on 2024-06-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_usertransaction_user_alter_advertisement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
